import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import path from "path";

const dbPath = path.join(process.cwd(), "prisma", "dev.db");
const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter } as ConstructorParameters<typeof PrismaClient>[0]);

async function main() {
  // Clear existing data
  await prisma.blogPost.deleteMany();
  await prisma.listing.deleteMany();

  // Seed listings
  await prisma.listing.createMany({
    data: [
      {
        id: "1",
        mlsNumber: "27834521",
        address: "4210 Rue Saint-Denis, app. 3",
        neighborhood: "Plateau-Mont-Royal",
        city: "Montréal",
        price: 589000,
        priceReduced: false,
        type: "Condo",
        status: "Active",
        isNew: true,
        beds: 2,
        baths: 1,
        sqft: 985,
        parking: 1,
        yearBuilt: 1910,
        condoFees: 320,
        taxes: 3200,
        description:
          "Magnificent renovated condo in the heart of Plateau-Mont-Royal. This charming 2-bedroom unit features original exposed brick walls, hardwood floors throughout, and a private balcony overlooking a quiet courtyard. Renovated kitchen with quartz countertops and stainless steel appliances. Walking distance to Parc Lafontaine, trendy restaurants, and boutiques on Mont-Royal Ave.",
        features: JSON.stringify([
          "Hardwood floors",
          "Exposed brick walls",
          "Private balcony",
          "Renovated kitchen",
          "In-unit washer/dryer",
          "Storage locker",
          "Walk-in closet",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1560185008-b033106af5c3?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-06-11",
      },
      {
        id: "2",
        mlsNumber: "27901234",
        address: "238 Av. Dufresne",
        neighborhood: "Westmount",
        city: "Montréal",
        price: 1850000,
        priceReduced: false,
        type: "House",
        status: "Active",
        isNew: false,
        beds: 4,
        baths: 3,
        sqft: 3200,
        parking: 2,
        yearBuilt: 1935,
        taxes: 12800,
        description:
          "Stunning Victorian detached home on one of Westmount's most prestigious streets. Meticulously preserved original details — stained glass windows, ornate fireplaces, and original hardwood — blend seamlessly with a fully renovated chef's kitchen and spa-inspired bathrooms. Exceptional south-facing backyard garden. Just steps from Victoria Village and Westmount Park.",
        features: JSON.stringify([
          "Original fireplaces (3)",
          "Chef's kitchen",
          "Stained glass windows",
          "Finished basement",
          "2-car garage",
          "Private garden",
          "Home office",
          "Smart home system",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-05-28",
      },
      {
        id: "3",
        mlsNumber: "27765432",
        address: "1080 Rue Wellington, suite 412",
        neighborhood: "Griffintown",
        city: "Montréal",
        price: 449000,
        priceReduced: false,
        type: "Condo",
        status: "Active",
        isNew: true,
        beds: 1,
        baths: 1,
        sqft: 720,
        parking: 1,
        yearBuilt: 2021,
        condoFees: 410,
        taxes: 2700,
        description:
          "Brand-new corner unit in Griffintown's most sought-after building. Floor-to-ceiling windows with panoramic views of the Lachine Canal and city skyline. Open-concept layout with designer finishes throughout. Amenities include rooftop terrace, gym, concierge, and EV charging stations. Walking distance to the canal bike path and dozens of restaurants.",
        features: JSON.stringify([
          "Floor-to-ceiling windows",
          "Canal & skyline views",
          "Rooftop terrace access",
          "Fitness centre",
          "Concierge service",
          "EV charging",
          "Bike storage",
          "BBQ area",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-06-14",
      },
      {
        id: "4",
        mlsNumber: "27654321",
        address: "55 Av. Querbes",
        neighborhood: "Outremont",
        city: "Montréal",
        price: 1200000,
        priceReduced: true,
        previousPrice: 1349000,
        type: "Duplex",
        status: "Active",
        isNew: false,
        beds: 5,
        baths: 3,
        sqft: 2800,
        parking: 2,
        yearBuilt: 1922,
        taxes: 8400,
        description:
          "Rare opportunity to own an income-generating duplex in the coveted Outremont neighbourhood. The upper unit (owner's unit) features 3 bedrooms, a sun-drenched living room with original oak floors, and a newly renovated kitchen. The lower unit is a bright 2-bedroom currently leased. Large private backyard, garage, and driveway. Steps from Parc Beaubien and all local amenities.",
        features: JSON.stringify([
          "Income property",
          "Original oak floors",
          "Renovated kitchens",
          "2-car garage",
          "Private backyard",
          "Upper/lower duplex",
          "Separate entrances",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-04-10",
      },
      {
        id: "5",
        mlsNumber: "27543210",
        address: "5432 Blvd Saint-Laurent, app. 201",
        neighborhood: "Mile-End",
        city: "Montréal",
        price: 399000,
        priceReduced: false,
        type: "Condo",
        status: "Active",
        isNew: false,
        beds: 1,
        baths: 1,
        sqft: 650,
        parking: 0,
        yearBuilt: 1965,
        condoFees: 280,
        taxes: 2300,
        description:
          "Hip and charming condo steps from the best of the Mile-End. Bright and airy with large windows, polished concrete floors, and an exposed ductwork aesthetic that defines the neighbourhood's cool creative vibe. Renovated bathroom, newer appliances, and a private terrace perfect for morning coffee. Bagels, cafés, and boutiques right at your door.",
        features: JSON.stringify([
          "Polished concrete floors",
          "Private terrace",
          "Exposed ductwork aesthetic",
          "Renovated bathroom",
          "Large windows",
          "Bike-friendly building",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1505873242700-f289a29e1724?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-05-05",
      },
      {
        id: "6",
        mlsNumber: "27432109",
        address: "309 Rue de Verdun",
        neighborhood: "Verdun",
        city: "Montréal",
        price: 699000,
        priceReduced: false,
        type: "Townhouse",
        status: "Active",
        isNew: false,
        beds: 3,
        baths: 2,
        sqft: 1450,
        parking: 1,
        yearBuilt: 2018,
        condoFees: 180,
        taxes: 4400,
        description:
          "Modern townhouse in rapidly appreciating Verdun, just 2 blocks from the St. Lawrence River waterfront. Built in 2018 with contemporary finishes — quartz kitchen island, heated bathroom floors, and a private rooftop terrace with gas hookup. The partially finished basement offers excellent additional space. Close to the new Verdun Auditorium arena and LaSalle metro.",
        features: JSON.stringify([
          "Private rooftop terrace",
          "Heated bathroom floors",
          "Quartz kitchen island",
          "Partially finished basement",
          "Gas BBQ hookup",
          "2 blocks from river",
          "Smart thermostat",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-05-19",
      },
      {
        id: "7",
        mlsNumber: "27321098",
        address: "6720 Av. Monkland",
        neighborhood: "NDG",
        city: "Montréal",
        price: 795000,
        priceReduced: false,
        type: "House",
        status: "Pending",
        isNew: false,
        beds: 3,
        baths: 2,
        sqft: 1800,
        parking: 1,
        yearBuilt: 1948,
        taxes: 5600,
        description:
          "Charming semi-detached on a tree-lined street in the heart of NDG — one of Montréal's most beloved family neighbourhoods. Generous open-plan main floor, updated eat-in kitchen, and 3 well-proportioned bedrooms. Covered front porch, large backyard with mature trees, and an attached garage. Walking distance to Monkland Village shops and Girouard Park.",
        features: JSON.stringify([
          "Tree-lined street",
          "Covered front porch",
          "Large backyard",
          "Attached garage",
          "Updated kitchen",
          "Mature trees",
          "Near Monkland Village",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-05-02",
      },
      {
        id: "8",
        mlsNumber: "27210987",
        address: "2145 Rue Beaubien E, app. 8",
        neighborhood: "Rosemont",
        city: "Montréal",
        price: 459000,
        priceReduced: true,
        previousPrice: 499000,
        type: "Condo",
        status: "Active",
        isNew: true,
        beds: 2,
        baths: 1,
        sqft: 850,
        parking: 1,
        yearBuilt: 1990,
        condoFees: 295,
        taxes: 2900,
        description:
          "Beautifully updated condo in vibrant Rosemont-La Petite-Patrie. This corner unit is flooded with natural light from its east and south exposures. Updated kitchen with butcher block counters, renovated bathroom with glass shower, and original parquet flooring. Steps from the Beaubien Market, Jean-Talon Market, bike paths, and Little Italy. Price just reduced — won't last!",
        features: JSON.stringify([
          "Corner unit — dual exposure",
          "Original parquet floors",
          "Butcher block kitchen",
          "Glass shower",
          "Near Jean-Talon Market",
          "Bike path access",
          "Storage locker",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-06-15",
      },
      {
        id: "9",
        mlsNumber: "27109876",
        address: "3580 Ch. Queen-Mary",
        neighborhood: "Côte-des-Neiges",
        city: "Montréal",
        price: 950000,
        priceReduced: false,
        type: "House",
        status: "Active",
        isNew: false,
        beds: 4,
        baths: 2,
        sqft: 2200,
        parking: 1,
        yearBuilt: 1958,
        taxes: 6800,
        description:
          "Spacious 4-bedroom detached home in the heart of Côte-des-Neiges, steps from Université de Montréal campus and Snowdon metro station. The main floor features a generous living-dining area with a wood-burning fireplace, a large updated kitchen, and a sunny family room addition. The finished basement offers a full apartment for rental income or extended family.",
        features: JSON.stringify([
          "Wood-burning fireplace",
          "4-season sunroom addition",
          "Finished basement apartment",
          "Updated kitchen",
          "Near Université de Montréal",
          "Walking distance to metro",
          "Large private yard",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-05-14",
      },
      {
        id: "10",
        mlsNumber: "27098765",
        address: "400 Rue de la Commune O, suite 602",
        neighborhood: "Old Montréal",
        city: "Montréal",
        price: 789000,
        priceReduced: false,
        type: "Loft",
        status: "Active",
        isNew: false,
        beds: 2,
        baths: 2,
        sqft: 1350,
        parking: 1,
        yearBuilt: 1888,
        condoFees: 620,
        taxes: 5200,
        description:
          "Spectacular heritage loft in a converted 19th-century warehouse on the Old Port waterfront. Soaring 14-foot ceilings, original timber beams, factory windows, and wide-plank pine floors make this one of Old Montréal's most extraordinary residences. Two full bathrooms, a gourmet kitchen, and a private terrace overlooking the St. Lawrence River. Building includes concierge, gym, and indoor parking.",
        features: JSON.stringify([
          "14-foot ceilings",
          "Original timber beams",
          "Factory windows",
          "Wide-plank pine floors",
          "Private river-view terrace",
          "Gourmet kitchen",
          "Heritage building (1888)",
          "24/7 concierge",
        ]),
        images: JSON.stringify([
          "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&auto=format&fit=crop",
          "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=900&auto=format&fit=crop",
        ]),
        listedDate: "2026-04-22",
      },
    ],
  });

  // Seed blog posts
  const blogPosts = [
    {
      slug: "is-2026-a-good-time-to-buy-in-montreal",
      titleEn: "Is 2026 a Good Year to Buy in Montréal?",
      titleFr: "Est-il le bon moment d'acheter à Montréal en 2026 ?",
      excerptEn:
        "After two years of rate adjustments and market recalibration, Montréal's real estate market is entering a new phase. Here's my honest assessment of where we stand and what buyers should expect.",
      excerptFr:
        "Après deux années d'ajustements de taux et de recalibration du marché, l'immobilier montréalais entre dans une nouvelle phase. Voici mon évaluation honnête de la situation et ce à quoi les acheteurs peuvent s'attendre.",
      bodyEn: JSON.stringify([
        "After two years of rate hikes and market cooling, Montréal's real estate market is showing signs of renewed stability. The Bank of Canada's rate normalization cycle appears to be winding down, and inventory levels are gradually improving — creating windows of opportunity for buyers who have been sitting on the sidelines.",
        "According to the latest QPAREB data, median condo prices on the Île-de-Montréal have stabilized between $430,000 and $480,000, while single-family homes hover around $750,000 in central neighbourhoods. These figures represent modest gains compared to the peak years of 2021–2022, but the frenzied bidding wars of that era are largely behind us.",
        "For first-time buyers, the timing is particularly interesting. The federal First Home Savings Account (FHSA) allows you to accumulate up to $40,000 tax-free specifically for a home purchase. Combined with the RRSP Home Buyers' Plan ($35,000 per person), a couple could access up to $150,000 in tax-advantaged savings toward a down payment.",
        "Fixed five-year rates have settled into a range that makes homeownership viable for well-qualified buyers — especially those who can put down 20% or more. Variable rates are expected to decrease further through 2026 as the Bank of Canada continues its easing cycle, which could make variable-rate mortgages attractive again.",
        "My professional assessment: 2026 is a solid year for buyers who are financially prepared. The market is active but not frenzied. You have time to be selective, to negotiate conditions, and to conduct proper due diligence. If you've been waiting for the 'right moment,' this is as close as the market gets.",
      ]),
      bodyFr: JSON.stringify([
        "Après deux années de hausses de taux et de refroidissement du marché, l'immobilier montréalais montre des signes de stabilité retrouvée. Le cycle de normalisation des taux de la Banque du Canada semble tirer à sa fin, et les niveaux d'inventaire s'améliorent graduellement — créant des occasions pour les acheteurs qui attendaient en marge.",
        "Selon les dernières données de l'APCIQ, les prix médians des copropriétés sur l'île de Montréal se sont stabilisés entre 430 000 $ et 480 000 $, tandis que les maisons unifamiliales avoisinent les 750 000 $ dans les quartiers centraux. Ces chiffres représentent des gains modestes par rapport aux années de pointe 2021-2022, mais les guerres d'enchères frénétiques de cette époque sont largement derrière nous.",
        "Pour les premiers acheteurs, le moment est particulièrement intéressant. Le Compte d'épargne libre d'impôt pour l'achat d'une première propriété (CELIAPP) vous permet d'accumuler jusqu'à 40 000 $ en franchise d'impôt. Combiné au RAP du REER (35 000 $ par personne), un couple pourrait accéder à 150 000 $ en épargne à avantages fiscaux pour sa mise de fonds.",
        "Les taux fixes sur cinq ans se sont stabilisés dans une fourchette qui rend l'accession à la propriété viable pour les acheteurs bien qualifiés — surtout ceux qui peuvent verser une mise de fonds de 20 % ou plus. Les taux variables devraient continuer de baisser en 2026, ce qui pourrait les rendre à nouveau intéressants.",
        "Mon évaluation professionnelle : 2026 est une bonne année pour les acheteurs financièrement préparés. Le marché est actif mais non frénétique. Vous avez le temps d'être sélectif, de négocier des conditions et de faire preuve d'une diligence raisonnable adéquate. Si vous attendiez le 'bon moment', c'est aussi proche que le marché peut l'être.",
      ]),
      categoryEn: "Market Update",
      categoryFr: "Actualité du marché",
      image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=900&auto=format&fit=crop",
      date: "2026-06-10",
      readTime: 5,
    },
    {
      slug: "top-5-neighbourhoods-montreal-2026",
      titleEn: "Top 5 Montréal Neighbourhoods to Watch in 2026",
      titleFr: "Les 5 quartiers de Montréal à surveiller en 2026",
      excerptEn:
        "From Verdun's waterfront revival to Rosemont's enduring charm, these five neighbourhoods offer the best balance of lifestyle, value, and growth potential right now.",
      excerptFr:
        "Du renouveau du bord de l'eau à Verdun au charme intemporel de Rosemont, ces cinq quartiers offrent le meilleur équilibre entre style de vie, valeur et potentiel de croissance.",
      bodyEn: JSON.stringify([
        "Every year I get asked the same question: 'Which neighbourhood should I be looking at?' The honest answer is that it depends entirely on your lifestyle, budget, and investment horizon. But in 2026, five areas stand out as offering exceptional value or strong momentum.",
        "Verdun has transformed remarkably over the past decade. Once overlooked, this riverside neighbourhood now boasts a vibrant Wellington Street corridor, stunning St. Lawrence River access, and some of the best condo-to-price ratios on the island. Young families and professionals are flocking here.",
        "Rosemont–La Petite-Patrie remains one of the most consistently sought-after areas in Montréal. Tree-lined streets, a thriving arts and food scene, and excellent transit access make it perpetually appealing. Prices have softened slightly from 2022 peaks, making this a rare re-entry opportunity.",
        "Saint-Henri has evolved from a working-class neighbourhood into one of Montréal's most exciting emerging enclaves. The Lachine Canal corridor offers cycling access to downtown, while new restaurants and galleries have raised the area's profile considerably.",
        "Villeray rounds out my list with its spacious homes, authentic community feel, and prices that still feel accessible by central Montréal standards. It tends to attract buyers who want the Plateau lifestyle without the Plateau price tag.",
      ]),
      bodyFr: JSON.stringify([
        "Chaque année, on me pose la même question : 'Quel quartier devrais-je cibler ?' La réponse honnête est que cela dépend entièrement de votre style de vie, de votre budget et de votre horizon d'investissement. Mais en 2026, cinq secteurs se distinguent par leur valeur exceptionnelle ou leur dynamisme.",
        "Verdun s'est remarquablement transformé au cours de la dernière décennie. Autrefois négligé, ce quartier riverain possède désormais un corridor Wellington animé, un accès exceptionnel aux berges du Saint-Laurent et certains des meilleurs rapports condo-prix de l'île. Les jeunes familles et professionnels s'y installent en masse.",
        "Rosemont–La Petite-Patrie demeure l'un des secteurs les plus convoités de Montréal. Les rues bordées d'arbres, une scène artistique et gastronomique florissante et un excellent accès aux transports en commun le rendent perpétuellement attrayant. Les prix ont légèrement fléchi depuis les sommets de 2022, créant une rare occasion de réentrée.",
        "Saint-Henri a évolué d'un quartier ouvrier à l'un des enclaves émergentes les plus excitantes de Montréal. Le corridor du canal Lachine offre un accès cyclable au centre-ville, tandis que de nouveaux restaurants et galeries ont considérablement rehaussé le profil du secteur.",
        "Villeray complète ma liste avec ses maisons spacieuses, son authenticité communautaire et des prix qui demeurent accessibles selon les standards du centre de Montréal. Il attire les acheteurs qui souhaitent le style de vie du Plateau sans le prix du Plateau.",
      ]),
      categoryEn: "Neighbourhoods",
      categoryFr: "Quartiers",
      image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=900&auto=format&fit=crop",
      date: "2026-05-28",
      readTime: 4,
    },
    {
      slug: "how-to-prepare-your-home-for-sale",
      titleEn: "How to Prepare Your Home for Sale: The Complete Guide",
      titleFr: "Comment préparer votre propriété pour la vente : le guide complet",
      excerptEn:
        "Preparation is worth more than price reduction. Homes that are properly staged and professionally photographed sell for 5–10% more. Here's exactly what to do — and what to skip.",
      excerptFr:
        "La préparation vaut plus qu'une réduction de prix. Les propriétés bien mises en valeur et photographiées professionnellement se vendent 5 à 10 % plus cher. Voici exactement ce qu'il faut faire — et ce qu'il faut éviter.",
      bodyEn: JSON.stringify([
        "The single biggest mistake sellers make is underinvesting in preparation. In my 12+ years of selling Montréal properties, I've seen time and again that a well-prepared home attracts more buyers, generates multiple offers, and ultimately sells for more money than its unprepared competition — even at a higher asking price.",
        "Start with decluttering — aggressively. Buyers need to mentally move into your home, and that's hard when every surface is occupied. Rent a storage unit if necessary. Then address all minor repairs: running toilets, sticky doors, cracked caulking, burnt-out bulbs. These small issues signal neglect and give buyers negotiating ammunition.",
        "Staging is not about decorating — it's about storytelling. Each room should communicate a clear lifestyle aspiration. Neutral, warm tones tend to appeal to the broadest audience. If you've lived with bold paint colors or eclectic furniture, a professional stager can help you see your home through a buyer's eyes.",
        "Professional photography is non-negotiable in today's market. Over 90% of buyers begin their search online, and your listing photos are your first impression. I include professional photography, floor plans, and a virtual tour with every listing I represent — because I've seen the difference it makes.",
        "Finally, price it right from the start. An overpriced listing loses its freshest, most motivated buyers in the first two weeks. A correctly priced home generates urgency and can lead to multiple offers. Getting the pricing strategy right is where my market analysis adds the most value.",
      ]),
      bodyFr: JSON.stringify([
        "La plus grande erreur des vendeurs est de sous-investir dans la préparation. En plus de 12 ans de vente de propriétés montréalaises, j'ai constaté à maintes reprises qu'une propriété bien préparée attire plus d'acheteurs, génère des offres multiples et se vend ultimement pour plus d'argent que sa concurrence non préparée — même à un prix demandé plus élevé.",
        "Commencez par désencombrer — agressivement. Les acheteurs doivent pouvoir s'imaginer vivre dans votre maison, ce qui est difficile quand chaque surface est occupée. Louez une unité d'entreposage si nécessaire. Puis, réglez toutes les réparations mineures : toilettes qui coulent, portes récalcitrantes, joints de calfeutrage fissurés, ampoules grillées.",
        "La mise en scène ne consiste pas à décorer, mais à raconter une histoire. Chaque pièce doit communiquer une aspiration de style de vie claire. Les tons neutres et chauds tendent à plaire au plus grand nombre d'acheteurs. Si vous avez des couleurs vives ou des meubles éclectiques, un styliste professionnel peut vous aider à voir votre maison avec les yeux d'un acheteur.",
        "La photographie professionnelle est incontournable dans le marché actuel. Plus de 90 % des acheteurs commencent leur recherche en ligne, et vos photos de propriété sont votre première impression. J'inclus photographie professionnelle, plans d'étage et visite virtuelle dans chaque inscription que je représente.",
        "Finalement, établissez le bon prix dès le départ. Une propriété surévaluée perd ses acheteurs les plus motivés dans les deux premières semaines. Une propriété correctement évaluée génère de l'urgence et peut mener à des offres multiples. C'est là que mon analyse de marché ajoute le plus de valeur.",
      ]),
      categoryEn: "Seller Tips",
      categoryFr: "Conseils aux vendeurs",
      image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&auto=format&fit=crop",
      date: "2026-05-14",
      readTime: 6,
    },
    {
      slug: "first-time-buyer-guide-quebec",
      titleEn: "The Complete First-Time Buyer Guide in Québec",
      titleFr: "Guide complet de l'acheteur pour la première fois au Québec",
      excerptEn:
        "From FHSA to the notary, here is everything you need to know about buying your first home in Québec — explained clearly, without the jargon.",
      excerptFr:
        "Du CELIAPP au notaire, voici tout ce que vous devez savoir pour acheter votre première propriété au Québec — expliqué clairement, sans jargon.",
      bodyEn: JSON.stringify([
        "Buying your first home is one of the most significant financial decisions you'll make, and Québec has its own distinct legal and financial ecosystem around real estate. Understanding these specifics before you start will save you time, money, and stress.",
        "The First Home Savings Account (FHSA) is the most powerful new tool for first-time buyers. Introduced in 2023, it allows you to contribute up to $8,000 per year (lifetime limit $40,000) and deduct contributions from your taxable income. Withdrawals for a qualifying home purchase are completely tax-free. Combined with the RRSP Home Buyers' Plan, a couple can access up to $150,000 tax-advantaged.",
        "In Québec, real estate transactions are completed by a notary, not a real estate lawyer. The notary is neutral — they represent the transaction, not either party. Their fee (typically $1,200–$2,000) covers the deed of sale, title search, and disbursements. Plan for land transfer tax (the 'welcome tax') as well: in Montréal, this ranges from 0.5% to 2.0% depending on the property value.",
        "Your pre-approval is your most important first step. It tells you exactly what you can afford, strengthens your offers, and allows you to move quickly in competitive situations. Work with a mortgage broker who can access multiple lenders — they often find better rates than going directly to your bank.",
        "Finally, don't skip the inspection. In competitive markets, there's sometimes pressure to waive conditions, but the building inspection protects you from hidden defects. A good inspector will give you peace of mind or leverage to renegotiate. It's money exceptionally well spent.",
      ]),
      bodyFr: JSON.stringify([
        "Acheter votre première propriété est l'une des décisions financières les plus importantes que vous prendrez, et le Québec possède son propre écosystème juridique et financier distinct en matière d'immobilier. Comprendre ces spécificités avant de commencer vous fera économiser du temps, de l'argent et du stress.",
        "Le Compte d'épargne libre d'impôt pour l'achat d'une première propriété (CELIAPP) est le nouvel outil le plus puissant pour les premiers acheteurs. Introduit en 2023, il vous permet de cotiser jusqu'à 8 000 $ par an (limite à vie de 40 000 $) et de déduire les cotisations de votre revenu imposable. Les retraits pour un achat admissible sont entièrement non imposables.",
        "Au Québec, les transactions immobilières sont complétées par un notaire, et non par un avocat spécialisé en immobilier. Le notaire est neutre — il représente la transaction, et non l'une ou l'autre des parties. Ses honoraires (généralement 1 200 $ à 2 000 $) couvrent l'acte de vente, la recherche de titre et les déboursés. Prévoyez également la taxe de bienvenue : à Montréal, elle varie de 0,5 % à 2,0 % selon la valeur de la propriété.",
        "Votre préapprobation est la première étape la plus importante. Elle vous indique exactement ce que vous pouvez vous permettre, renforce vos offres et vous permet d'agir rapidement dans des situations concurrentielles. Travaillez avec un courtier hypothécaire qui peut accéder à plusieurs prêteurs.",
        "Finalement, ne renoncez pas à l'inspection. Dans les marchés concurrentiels, il y a parfois une pression pour renoncer aux conditions, mais l'inspection du bâtiment vous protège des défauts cachés. Un bon inspecteur vous donnera la tranquillité d'esprit ou un levier pour renégocier. C'est de l'argent exceptionnellement bien dépensé.",
      ]),
      categoryEn: "Buyer Tips",
      categoryFr: "Conseils aux acheteurs",
      image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=900&auto=format&fit=crop",
      date: "2026-04-30",
      readTime: 7,
    },
    {
      slug: "condo-vs-house-montreal",
      titleEn: "Condo vs. House in Montréal: Which is Right for You?",
      titleFr: "Condo ou maison à Montréal : qu'est-ce qui vous convient ?",
      excerptEn:
        "Both offer compelling advantages depending on your lifestyle and financial goals. Here's a frank comparison to help you decide — with real numbers from the current Montréal market.",
      excerptFr:
        "Les deux offrent des avantages convaincants selon votre style de vie et vos objectifs financiers. Voici une comparaison franche pour vous aider à décider — avec de vrais chiffres du marché montréalais actuel.",
      bodyEn: JSON.stringify([
        "The condo-versus-house debate is one of the most common conversations I have with buyers. The right answer depends less on abstract principles and more on your specific situation: your lifestyle, your five-year plan, your tolerance for maintenance, and ultimately your budget.",
        "Condos in Montréal range from $300,000 studios in emerging neighbourhoods to $2M+ penthouses in Griffintown or the Golden Square Mile. The key advantage is lifestyle: concierge, amenities, no exterior maintenance, and central urban locations. The key trade-off is monthly condo fees (typically $300–$700+) and the loss of complete autonomy over your space.",
        "Single-family homes offer space, privacy, and typically more appreciation over the long term in established neighbourhoods. The tradeoff is higher purchase prices, greater maintenance responsibility, and in Montréal specifically, the challenge of finding good central-island homes under $800,000. Duplexes are a compelling middle ground — you get space while the rental income helps cover carrying costs.",
        "From a pure investment standpoint, both asset classes have performed well over the past decade in Montréal. Condos in the $400K–$600K range in desirable urban neighbourhoods have appreciated solidly and offer strong rental demand. Houses in Rosemont, Villeray, and similar areas have seen even stronger appreciation but require more capital.",
        "My recommendation: think about your life in five years. If you value flexibility, low maintenance, and urban convenience, a well-chosen condo is likely the smarter move. If you're planning to stay put, have or anticipate a family, and want to build long-term equity in a tangible asset, a house or triplex is worth the higher entry cost.",
      ]),
      bodyFr: JSON.stringify([
        "Le débat condo contre maison est l'une des conversations les plus courantes que j'ai avec les acheteurs. La bonne réponse dépend moins de principes abstraits que de votre situation spécifique : votre style de vie, votre plan sur cinq ans, votre tolérance pour l'entretien et, en fin de compte, votre budget.",
        "Les condos à Montréal vont des studios à 300 000 $ dans les quartiers émergents aux penthouses à 2 M$+ à Griffintown ou dans le Mille carré doré. L'avantage clé est le style de vie : concierge, commodités, aucun entretien extérieur et des emplacements urbains centraux. Le compromis clé est les frais de condo mensuels (généralement 300 $ à 700 $+).",
        "Les maisons unifamiliales offrent de l'espace, de l'intimité et, en général, une meilleure appréciation à long terme dans les quartiers établis. Le compromis est des prix d'achat plus élevés et une plus grande responsabilité d'entretien. Les duplex constituent un juste milieu intéressant — vous obtenez de l'espace tandis que le revenu locatif aide à couvrir les frais de portage.",
        "D'un point de vue purement investissement, les deux catégories d'actifs ont bien performé au cours de la dernière décennie à Montréal. Les condos dans la fourchette de 400 000 $ à 600 000 $ dans des quartiers urbains désirables ont connu une solide appréciation et offrent une forte demande locative.",
        "Ma recommandation : pensez à votre vie dans cinq ans. Si vous valorisez la flexibilité, le faible entretien et la commodité urbaine, un condo bien choisi est probablement le choix le plus judicieux. Si vous prévoyez rester en place, avez ou anticipez une famille, et souhaitez bâtir des capitaux propres à long terme, une maison ou un triplex vaut le coût d'entrée plus élevé.",
      ]),
      categoryEn: "Buyer Tips",
      categoryFr: "Conseils aux acheteurs",
      image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&auto=format&fit=crop",
      date: "2026-04-15",
      readTime: 5,
    },
    {
      slug: "negotiation-strategies-montreal",
      titleEn: "5 Negotiation Strategies That Get Results in Montréal",
      titleFr: "5 stratégies de négociation qui donnent des résultats à Montréal",
      excerptEn:
        "Negotiation is where most buyers either leave money on the table or lose the deal. After 12 years and hundreds of transactions, here are the strategies I rely on most.",
      excerptFr:
        "La négociation est là où la plupart des acheteurs laissent de l'argent sur la table ou perdent la transaction. Après 12 ans et des centaines de transactions, voici les stratégies sur lesquelles je compte le plus.",
      bodyEn: JSON.stringify([
        "Real estate negotiation in Montréal is not a single event — it's a process that begins the moment you first see a property and continues until the deed is signed. The buyers who consistently get the best outcomes aren't the most aggressive; they're the most prepared.",
        "Strategy 1: Know the seller's motivation. A seller who is moving for a job relocation cares deeply about certainty and timeline. A seller downsizing after retirement cares about price. A seller in financial distress cares about speed. Understanding what the seller truly needs lets you structure an offer that works for both sides.",
        "Strategy 2: Use conditions strategically, not reflexively. Every condition you include slightly weakens your offer in a seller's eyes. Include the conditions that genuinely matter to you — financing, inspection — and be prepared to be flexible on those that don't. The right conditions protect you; the wrong ones cost you deals.",
        "Strategy 3: Move on imperfect information quickly. Waiting until you have certainty is waiting until the deal is gone. In active markets, you often have 24–48 hours to decide. Trust your preparation, trust your instincts, and trust your agent's read of the market.",
        "Strategy 4: The first offer sets the tone. Coming in too low rarely gets you a deal — it usually offends the seller and poisons the negotiation. A serious, well-structured first offer signals you're a genuine buyer and creates goodwill that often pays off in other aspects of the deal.",
        "Strategy 5: Know when to walk away — and mean it. The best negotiating position is genuine willingness to leave if the terms aren't right. This isn't a bluff; it's a mindset. When sellers sense that you'll accept almost anything to get the property, your leverage evaporates entirely.",
      ]),
      bodyFr: JSON.stringify([
        "La négociation immobilière à Montréal n'est pas un événement unique — c'est un processus qui commence dès le moment où vous voyez une propriété et se poursuit jusqu'à la signature de l'acte. Les acheteurs qui obtiennent systématiquement les meilleurs résultats ne sont pas les plus agressifs ; ils sont les plus préparés.",
        "Stratégie 1 : Connaître la motivation du vendeur. Un vendeur qui déménage pour un emploi se soucie profondément de la certitude et du calendrier. Un vendeur qui réduit la taille de sa maison à la retraite se soucie du prix. Un vendeur en difficulté financière se soucie de la rapidité.",
        "Stratégie 2 : Utiliser les conditions stratégiquement, pas réflexivement. Chaque condition que vous incluez affaiblit légèrement votre offre aux yeux du vendeur. Incluez les conditions qui comptent vraiment pour vous — financement, inspection — et soyez prêt à être flexible sur celles qui ne le sont pas.",
        "Stratégie 3 : Agir rapidement sur des informations imparfaites. Attendre d'avoir la certitude, c'est attendre que l'occasion soit passée. Dans les marchés actifs, vous avez souvent 24 à 48 heures pour décider.",
        "Stratégie 4 : La première offre donne le ton. Commencer trop bas donne rarement une entente — cela offense généralement le vendeur et empoisonne la négociation. Une première offre sérieuse et bien structurée signale que vous êtes un acheteur sérieux.",
        "Stratégie 5 : Savoir quand partir — et le penser vraiment. La meilleure position de négociation est une véritable volonté de partir si les conditions ne conviennent pas. Ce n'est pas un bluff ; c'est un état d'esprit.",
      ]),
      categoryEn: "Expert Advice",
      categoryFr: "Conseils d'expert",
      image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=900&auto=format&fit=crop",
      date: "2026-03-22",
      readTime: 6,
    },
  ];

  for (const post of blogPosts) {
    await prisma.blogPost.create({ data: post });
  }

  const listingCount = await prisma.listing.count();
  const blogCount = await prisma.blogPost.count();
  console.log(`Seeded ${listingCount} listings and ${blogCount} blog posts.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
